### ISSUE TITLE
Removing bottom tab when showing only gifs

### ISSUE THREAD

**Issue by qundrim** [Giphy/giphy-android-sdk-ui-example#101]
Im using the GiphyDialogFragment to show only gifs. Is there any way to remove the tab at the bottom when we decide to show only one type of mediaContent

**Comment by ALexanderLonsky** [comment]
@qundrim we'll fix that in the next release. I'll let you know when it's done.

**Comment by ALexanderLonsky** [comment]
@qundrim please try [this](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/v2.0.6) version.
