### ISSUE TITLE
Could not Customise the GiphyDialogFragment

### ISSUE THREAD

**Issue by RomanMoran** [Giphy/giphy-android-sdk-ui-example#102]
Trying to do like mentioned in documentation. 
https://github.com/Giphy/giphy-android-sdk-ui-example/blob/master/Docs.md#customise-the-giphydialogfragment
For example fill app values in black but no results.
Version that i used:
"com.giphy.sdk:ui:2.0.5"
How I initialize dialog:
![image](https://user-images.githubusercontent.com/25562234/100455645-1646c680-30d0-11eb-86ce-ec7101ecffe9.png)
Result:
![image](https://user-images.githubusercontent.com/25562234/100452807-ec3ed580-30ca-11eb-936f-25e1f5ee037d.png)

**Comment by ALexanderLonsky** [comment]
@RomanMoran I'll take a look and let you know.

For now I would blur your api key out on the first screenshot.

**Comment by ALexanderLonsky** [comment]
@RomanMoran what particular result you would like to achieve?

try please these ones:
```
<color name="gph_image_color_dark">#C09A9A9A</color>
<color name="gph_active_image_color_dark">#FF00FF99</color>
```

**Comment by RomanMoran** [comment]
`<color name="gph_active_image_color_dark">#FF00FF99</color>`
this param I wanted to change, you should add it to documentation if somebody wants to change thease buttons color.
![image](https://user-images.githubusercontent.com/25562234/100477689-1f4c8d80-30fa-11eb-977f-7361d2bf2bd2.png)

**Comment by RomanMoran** [comment]
`<color name="gph_active_image_color_dark">#FF00FF99</color>`
this param I wanted to change, you should add it to documentation if somebody wants to change thease buttons color.
![image](https://user-images.githubusercontent.com/25562234/100477689-1f4c8d80-30fa-11eb-977f-7361d2bf2bd2.png)
