### ISSUE TITLE
How to share gif directly from grid view ?

### ISSUE THREAD

**Issue by tejasbhatt17** [Giphy/giphy-android-sdk-ui-example#104]
Hello,

I like to use this lib for my app, how can I get gif to send ?

**Comment by ALexanderLonsky** [comment]
hello @tejasbhatt17,
please refer to [this](please refer to this documentation: ) section.

Also there is an example app.

**Comment by tejasbhatt17** [comment]
Hello @ALexanderLonsky 
Thanks for reply, I have checked that example and callback, but I don't know how to get gif file from that callback.
Can you please post example code to get gif file so I can share it on any social media ?

**Comment by ALexanderLonsky** [comment]
@tejasbhatt17 the SDK provides a gif url. You'll need to implement your own solution to fetch a file and use it for your needs.

**Comment by tejasbhatt17** [comment]
> @tejasbhatt17 the SDK provides a gif url. You'll need to implement your own solution to fetch a file and use it for your needs.

Thanks for reply

Yes, I get media object, but I am trying to get file from fresco cache, and for that I need to know which url getting cached.
So can you give me hint regarding this ?

**Comment by ALexanderLonsky** [comment]
@tejasbhatt17 I wouldn't be based on that cache. You can fetch it like [this](https://github.com/facebook/fresco/issues/2229#issuecomment-434061873)

Anyway, the SDK generate URL based on media rendition type and format, so it may vary.
For example for `gifs` you can get a file from cache in this way:

```
val url = media.images.original?.webPUrl.let {
        it.toString().replace("giphy.webp", "200w.webp")
} 
val imageRequest: ImageRequest? = ImageRequest.fromUri(loadUri)
val cacheKey: CacheKey = DefaultCacheKeyFactory.getInstance().getEncodedCacheKey(imageRequest, null)
val resource = ImagePipelineFactory.getInstance().mainFileCache.getResource(cacheKey)
```

**But I can't guarantee it won't change in the future, so please use your own solution to fetch files.**

**Comment by tejasbhatt17** [comment]
> @tejasbhatt17 I wouldn't be based on that cache. You can fetch a media file like [this](https://github.com/facebook/fresco/issues/2229#issuecomment-434061873)
> 
> Anyway, the SDK generate URL based on media rendition type and format, so it may vary.
> For example for `gifs` you can get a file from cache in this way:
> 
> ```
> val url = media.images.original?.webPUrl.let {
>         it.toString().replace("giphy.webp", "200w.webp")
> } 
> val imageRequest: ImageRequest? = ImageRequest.fromUri(loadUri)
> val cacheKey: CacheKey = DefaultCacheKeyFactory.getInstance().getEncodedCacheKey(imageRequest, null)
> val resource = ImagePipelineFactory.getInstance().mainFileCache.getResource(cacheKey)
> ```
> 
> **But I can't guarantee it won't change in the future, so please use your own solution to fetch files.**

Thanks for reply

I have created my own logic to download and share

**Comment by shubingo-android** [comment]
> > @tejasbhatt17 I wouldn't be based on that cache. You can fetch a media file like [this](https://github.com/facebook/fresco/issues/2229#issuecomment-434061873)
> > Anyway, the SDK generate URL based on media rendition type and format, so it may vary.
> > For example for `gifs` you can get a file from cache in this way:
> > ```
> > val url = media.images.original?.webPUrl.let {
> >         it.toString().replace("giphy.webp", "200w.webp")
> > } 
> > val imageRequest: ImageRequest? = ImageRequest.fromUri(loadUri)
> > val cacheKey: CacheKey = DefaultCacheKeyFactory.getInstance().getEncodedCacheKey(imageRequest, null)
> > val resource = ImagePipelineFactory.getInstance().mainFileCache.getResource(cacheKey)
> > ```
> > 
> > 
> > **But I can't guarantee it won't change in the future, so please use your own solution to fetch files.**
> 
> Thanks for reply
> 
> I have created my own logic to download and share



> @tejasbhatt17 I wouldn't be based on that cache. You can fetch a media file like [this](https://github.com/facebook/fresco/issues/2229#issuecomment-434061873)
> 
> Anyway, the SDK generate URL based on media rendition type and format, so it may vary.
> For example for `gifs` you can get a file from cache in this way:
> 
> ```
> val url = media.images.original?.webPUrl.let {
>         it.toString().replace("giphy.webp", "200w.webp")
> } 
> val imageRequest: ImageRequest? = ImageRequest.fromUri(loadUri)
> val cacheKey: CacheKey = DefaultCacheKeyFactory.getInstance().getEncodedCacheKey(imageRequest, null)
> val resource = ImagePipelineFactory.getInstance().mainFileCache.getResource(cacheKey)
> ```
> 
> **But I can't guarantee it won't change in the future, so please use your own solution to fetch files.**

I attempt to get the gifs cache like this,but the cache is Suffix with .cnt .why?
