### ISSUE TITLE
Is this a gphCellPadding bug?

### ISSUE THREAD

**Issue by KimDandan** [Giphy/giphy-android-sdk-ui-example#107]
Hi,
I am using GiphyGridView.
I set gphSpanCount to 5 and gphCellPadding to 20dp.
The size(width) of the items in (1, 5) column and (2, 3, 4) column looks different.
Is this normal? Or is it a bug?
please answer about my question.

**GIPHY sdk version:** 2.0.6
**device:** Samsung Galaxy S8 (Android9), Samsung Galaxy S10 (Android10)

**xml code :**
```
<com.giphy.sdk.ui.views.GiphyGridView
            android:id="@+id/sticker_list"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:gphCellPadding="20dp"
            app:gphDirection="vertical"
            app:gphShowCheckeredBackground="false"
            app:gphSpanCount="5"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
```

**Screenshot before/after cellPadding setting :**

![cell_padding_1](https://user-images.githubusercontent.com/75723737/101612615-2f476400-3a4e-11eb-8449-8cc392664c23.png)

![cell_padding_2](https://user-images.githubusercontent.com/75723737/101612625-32daeb00-3a4e-11eb-8cc0-fdac502dd147.png)

(If gphSpanCount is 3 or more and gphCellPadding is set, it seems that the size(width) of the items at both ends and the rest of the column will be different.)

**Comment by ALexanderLonsky** [comment]
@KimDandan hey, I'll look into this and let you know.

**Comment by ALexanderLonsky** [comment]
@KimDandan thanks for flagging this - i’ve been able to reproduce. i’ll include a fix in a future release.

**Comment by KimDandan** [comment]
@ALexanderLonsky Thank you for confirming!

**Comment by ALexanderLonsky** [comment]
@KimDandan please try [v2.0.7](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/v2.0.7)

**Comment by KimDandan** [comment]
@ALexanderLonsky I checked. Thanks.
