### ISSUE TITLE
How to add a view to the cell of the gifGridView

### ISSUE THREAD

**Issue by shubingo-android** [Giphy/giphy-android-sdk-ui-example#109]
When user click the cell of the GifGridView,we will download the special gif we want so we want to add a progress bar to the cell when the user is waiting to download,but I can not find the method to add a view in the cell like the recycleView.

**Comment by ALexanderLonsky** [comment]
@shubingo-android we have no plans to support this - i’ll pass on your request to my team.

**Comment by shubingo-android** [comment]
> @shubingo-android we have no plans to support this - i’ll pass on your request to my team.

@ALexanderLonsky  thanks for reply,Hope to add this feature, It will be more friendly and convenient to use
