### ISSUE TITLE
JPG link 

### ISSUE THREAD

**Issue by steevoo** [Giphy/giphy-android-sdk-ui-example#11]
Hi  ,I'm using 'com.giphy.sdk:ui:1.0.1' 
any idea how to get the JPG link of the GIF selected i didn't find it in the "Media" Object returned by the sdk while its available in the api response under the tag "480w_still"
and also its possible to access the physical file path stored of the selected GIF
thank you

**Comment by bogdantmm92** [comment]
Hey @steevoo, you could try `media.images.fixedWidthStill`. Let me know if that works.

**Comment by bogdantmm92** [comment]
In order to get the physical file path maybe it helps using the approach described here https://github.com/facebook/fresco/issues/235 .

**Comment by steevoo** [comment]
> 
> 
> Hey @steevoo, you could try `media.images.fixedWidthStill`. Let me know if that works.

thanks @bogdantmm92  'fixedWidthStill' its a jpg file  even the extension is gif
