### ISSUE TITLE
The content of method 'searchQuery(key,mediaType,RatingType)' returns wrong 

### ISSUE THREAD

**Issue by shubingo-android** [Giphy/giphy-android-sdk-ui-example#112]
GPHContent，What I pass is the query keyword of sticker, but sometimes it returns me the trending content of gif

**Comment by ALexanderLonsky** [comment]
@shubingo-android could you please provide the particular request/response so I can look into it?

**Comment by shubingo-android** [comment]
@ALexanderLonsky  I loaded it like this：
 private void loadGiphyContent() {
        try {
            if ("Trending".equals(mKey)) {
                mView.setGPHContent(TextUtils.equals(GIF_TYPE, mType)
                        ? GPHContent.Companion.getTrendingGifs() :
                        GPHContent.Companion.getTrendingStickers());
            } else {
                mView.setGPHContent(GPHContent.Companion.searchQuery(mKey, getMediaType(), RatingType.pg13));
            }
        } catch (Throwable e) {
            e.printStackTrace();
        }

    }

    private MediaType getMediaType() {
        if (mType.equals(GIF_TYPE)) {
            return GPHContentType.gif.getMediaType();
        } else {
            return GPHContentType.sticker.getMediaType();
        }
    }
    @Override
    public void setGPHContent(GPHContent content) {
        mGifGrideView.setContent(content);
    }
I checked the request and response ,the response is right, but When set to GiphyGridView, it sometimes displays trending content，This may happen to both gif and sticker.
Does GiphyGridView load the trending content of gif asynchronously by default. When the default loading is later than the content to be searched, it will display the gif trending content?Because I found it sometimes displays the trending content first, and then displays the correct content.

**Comment by ALexanderLonsky** [comment]
@shubingo-android yes, you are right. Please try this version: [2.0.8](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/v2.0.8)

**Comment by shubingo-android** [comment]
> @shubingo-android yes, you are right. Please try this version: [2.0.8](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/v2.0.8)

@ALexanderLonsky got it,I have updated to version 2.0.8, It's correct. Thanks!
