### ISSUE TITLE
search box and trending labels gets overlapped

### ISSUE THREAD

**Issue by perracolabs** [Giphy/giphy-android-sdk-ui-example#114]
Affected versions: 2.0.7 & 2.0.8
No issues in 2.0.6 and below.

When pressing the search text box, the list expands and cuts the the top search area.
See attached video.

https://user-images.githubusercontent.com/7354233/104822414-848f4600-5842-11eb-997b-16ecc0d2ce7f.mp4

**Comment by ALexanderLonsky** [comment]
@perracolabs are you able to reproduce this in the Giphy Example app? All versions work fine for me. Moreover, 2.0.7 as well as 2.0.8 do not have any changes that might be related to the issue. 
I'll double check that.

**Comment by perracolabs** [comment]
I will see if I can make a test project. 
I have the feeling, just a guess, that maybe this could be cause if by any chance you use the display metrics to perform the computations to resolve the expand height of the list, in such case this would wrong as the display metrics can be different depending on if an activity or fragment is full screen or not, there is a notch, etc. 
Although it can't be seen in the video, the device has a top notch.
The metrics should be computed based only on the container size, which I believe is a BottomSheet component.
But this is just a guess.

**Comment by ALexanderLonsky** [comment]
@perracolabs thank you for your reply, I'll look into this. 

_I will see if I can make a test project._
I would greatly appreciate it.

**Comment by perracolabs** [comment]
I could make a test project to reproduce the issue, (see attachment bellow), yet it needs a set of specific steps to force it.

1) Open the project and **before** pressing the test button, first **rotate the device to landscape**.
2) Press the **test** button, and once Giphy appears, **tap on the search box so it gets expanded to full screen**.
3) With Giphy still opened and expanded to full screen, **rotate the device to portrait**.
4) If the issue doesn't happen, then close giphy (not the app), and start again step 1, repeating until the issue is reproduced.

The issue seems to happen when a project handles configuration changes. In the test project I could simplify it to **orientation** and **screenSize**, although in our main project we also handle **keyboard** and **keyboardHidden**

    android:configChanges="orientation|screenSize"

and overriding the **onConfigurationChanged** activity method to handle these.

**Test Project**: [GiphyTest.zip](https://github.com/Giphy/giphy-android-sdk-ui-example/files/5829676/GiphyTest.zip)

To clarify the steps I've include also a video sample.
You will see **it happens only after the 3rd try (at 00:30 seconds)**, although testing it sometimes happens on the first one.
Yet, this test project is only to force the issue, and if you watch again the video in the original report, it wasn't necessary to rotate the device at all and it happens right away.

https://user-images.githubusercontent.com/7354233/104906733-629ddc80-5984-11eb-9bea-3fb0a37f02c4.mp4

**Comment by ALexanderLonsky** [comment]
@perracolabs thank you for the comprehensive reply, I'll take a look and get back to you.

**Comment by ALexanderLonsky** [comment]
@perracolabs it's weird, I was able to reproduce(using your test project) neither on a device nor in the simulator. 
I tried many times and even installed Google keyboard just in case.
Also I added `android:configChanges="orientation|screenSize"` along with `onConfigurationChanged` into my test project and was playing with `GiphyDialogFragment` constraints trying to reproduce the issue but everything works as expected.
What device and Android version do you use?
Can you try to disable suggestions bar(`GPHSettings.showSuggestionsBar=false`)?
Could you please share screens from `Layout Inspector`?

**Comment by perracolabs** [comment]
When setting **setShowSuggestionsBar** to **false** the issue can't be reproduced, so working correctly.

Find attached a few Inspector Layout screenshots.
I have highlighted the search area elements, so you can check the attribute metrics on the right panel.

The test device is a Huawei P20 Lite, API  28. 
Unfortunately I don't have access to other test devices at the present time.

[Screenshots.zip](https://github.com/Giphy/giphy-android-sdk-ui-example/files/5832765/Screenshots.zip)

**Comment by ALexanderLonsky** [comment]
@perracolabs hey, thank you for the update. Here is a new version: `com.giphy.sdk:ui:2.0.9-a.1`
Could you please check if the issue has gone for you?

**Comment by perracolabs** [comment]
Works correctly, with this new version can't reproduce the issue.

**Comment by ALexanderLonsky** [comment]
fixed in [v2.0.9](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/v2.0.9)
