### ISSUE TITLE
Stickers (transparent background GIF) are not showing after updating sdk

### ISSUE THREAD

**Issue by mihirmodiofficial** [Giphy/giphy-android-sdk-ui-example#115]
after updating to 'com.giphy.sdk:ui:2.0.7'
from older version 'com.giphy.sdk:ui:1.2.8'

its not showing sticker with transparent background

**Comment by ALexanderLonsky** [comment]
@mihirmodiofficial could you please give an example?

**Comment by mihirmodiofficial** [comment]
val settings = GPHSettings(GridType.waterfall, GPHTheme.Light)
            val gifsDialog = GiphyDialogFragment.newInstance(settings)
            settings.mediaTypeConfig = arrayOf(GPHContentType.sticker)
            settings.renditionType = RenditionType.fixedWidth
            settings.confirmationRenditionType = RenditionType.fixedHeight
            settings.showCheckeredBackground = false
            settings.useBlurredBackground = true
            settings.stickerColumnCount = 3
            settings.showSuggestionsBar = false
            gifsDialog.setTargetFragment(voucherDetailGifticonFragment, 0)
            gifsDialog.show(requireActivity.supportFragmentManager, "gifs_dialog")

**Comment by ALexanderLonsky** [comment]
@mihirmodiofficial I am sorry, I meant what particular stickers do not have transparent background? What search query do you use and what specific medias have issues?

**Comment by mihirmodiofficial** [comment]
No i donot search anything but in older version just by opening Dialog Fragment with above code its show gif with transparent background but in updated version its not.

**Comment by ALexanderLonsky** [comment]
Here are screenshots using v1.2.8:
<img width="715" alt="Screenshot 2021-01-19 at 13 16 28" src="https://user-images.githubusercontent.com/4112/105027832-e88b5780-5a58-11eb-838a-c389e2cc60f6.png">


And these are from v2.0.8:
<img width="724" alt="Screenshot 2021-01-19 at 13 18 48" src="https://user-images.githubusercontent.com/4112/105027897-fd67eb00-5a58-11eb-93e3-20411f726f31.png">



It seems all of them are transparent.

**Comment by ALexanderLonsky** [comment]
Ah, I got it. You mean that for `settings.mediaTypeConfig = arrayOf(GPHContentType.sticker)` it shows Gifs, not Stickers. 
I'll look into it.

**Comment by ALexanderLonsky** [comment]
@mihirmodiofficial it is a bug, as a workaround you can add the following:
`settings.selectedContentType = GPHContentType.sticker`

**Comment by mihirmodiofficial** [comment]
Thanks @ALexanderLonsky

**Comment by ALexanderLonsky** [comment]
fixed in [v2.0.9](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/v2.0.9)
