### ISSUE TITLE
Feature request: Sticky Suggestions Bar

### ISSUE THREAD

**Issue by perracolabs** [Giphy/giphy-android-sdk-ui-example#116]
Could you please add a configuration option to set the suggestions bar as sticky?
So, to be able to configure that the suggestions bar doesn't disappear when scrolling, and stays all the time visible under the search bar, regardless the scroll action.
The reason for this request is that after scrolling for a several seconds, it is required to scroll again all the way up to access it, which can take some time if the user scrolled for a while down.
As the suggestions bar doesn't take much space, it could be good to have a configuration setting to allow showing it always.

Thanks

**Comment by ALexanderLonsky** [comment]
@perracolabs please try this version: `com.giphy.sdk:ui:2.0.9-a.1`
a new option called `suggestionsBarFixedPosition`

**Comment by perracolabs** [comment]
Perfect

**Comment by ALexanderLonsky** [comment]
added in [v2.0.9](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/v2.0.9)
