### ISSUE TITLE
Giphy setMediaTypeConfig Order

### ISSUE THREAD

**Issue by colorgold** [Giphy/giphy-android-sdk-ui-example#12]
I am setting the media type configuration via this code in Android using java:
settings.setMediaTypeConfig(new GPHContentType[]{**GPHContentType.emoji**,GPHContentType.gif,GPHContentType.sticker,GPHContentType.text});

I want the emojis to be the first ones to load in the Giphy dialog, so I have added them in the array first. However, when I show the dialog, the gifs load first and I have to click on the Emoji tab again for the emojis to load correctly. Here is a screenshot of what I mean:

**On first load:**
![image](https://user-images.githubusercontent.com/45986859/66872095-c0b26780-ef6a-11e9-83bd-e6ff0976b015.png)

**After clicking the emoji tab:**
![image](https://user-images.githubusercontent.com/45986859/66872180-f9524100-ef6a-11e9-80a8-feaac5cad563.png)

How can I load the emojis when the dialog is first opened?

**Comment by Crysis21** [comment]
Hey @colorgold we will address this issue. Thanks for reporting.

**Comment by Crysis21** [comment]
@colorgold we are releasing 1.1.2 this afternoon and will contain a fix for this issue aswell.
