### ISSUE TITLE
Translate Search Bar

### ISSUE THREAD

**Issue by colorgold** [Giphy/giphy-android-sdk-ui-example#13]
How can I change the editText's hint in the GiphyDialogFragment to my own string value so that it is displayed in different languages?

![image](https://user-images.githubusercontent.com/45986859/67023489-8068fb80-f0c8-11e9-8961-96980e1db8cf.png)

**Comment by Crysis21** [comment]
Basically you can override the string resource in your project.
`@string/gph_search_giphy`

**Comment by perracolabs** [comment]
Are you planing to localize the SDK? Even though we can as you mention override "**gph_search_giphy**", actually we would have to translate  all the SDK strings for each language we support. **In addition to having to keep a watch in case you add/update/remove strings.** 

```
    <string name="gph_attibution_back">Back</string>
    <string name="gph_choose_emoji">Select Emoji</string>
    <string name="gph_choose_gif">Select GIF</string>
    <string name="gph_choose_sticker">Select Sticker</string>
    <string name="gph_copy">Copy</string>
    <string name="gph_copy_link">Copy Link</string>
    <string name="gph_emoji">Emoji</string>
    <string name="gph_error_generic_list_loading">Oh NO! Something Went Wrong.</string>
    <string name="gph_error_no_gifs_found">No GIFs found</string>
    <string name="gph_gifs">GIFs</string>
    <string name="gph_gifs_stickers"><![CDATA[Gifs & Stickers]]></string>
    <string name="gph_more_by">More by @%1$s</string>
    <string name="gph_more_creator">See more by creator</string>
    <string name="gph_recents">Recents</string>
    <string name="gph_remove">Remove</string>
    <string name="gph_results_count">%1$d results</string>
    <string name="gph_retry">Retry</string>
    <string name="gph_search_giphy">Search GIPHY</string>
    <string name="gph_search_giphy_stickers">Search GIPHY Stickers</string>
    <string name="gph_search_giphy_text">Search GIPHY Text</string>
    <string name="gph_share">Share</string>
    <string name="gph_stickers">Stickers</string>
    <string name="gph_text">Text</string>
    <string name="gph_view_on_giphy">View on GIPHY</string>
```

Side-note: **gph_results_count** would need special attention on the translations, as plurals and singulars can have a different localization depending on the language.

**Comment by Crysis21** [comment]
I'm sorry, but I'm no longer part of the Giphy team. I don't know what are the plans for the SDK.
