### ISSUE TITLE
Non static configre cannot be referenced from a static context

### ISSUE THREAD

**Issue by amiga** [Giphy/giphy-android-sdk-ui-example#14]
the very first line of your tutorial gives error, GiphyCoreUI.configure -> Non static configre cannot be referenced from a static context

**Comment by Crysis21** [comment]
Where do you try to initialize the SDK?

**Comment by amiga** [comment]
Sorry I did not realise it is written in Kotlin. Do you have an ordinary Android Java version of the SDK? or example on how to integrate with Java?

**Comment by Crysis21** [comment]
Kotlin is interchangable with Java. You can call kotlin code into Java code and vice-versa. Here is a basic Java example of initialization

```java

public class DemoJava extends AppCompatActivity {

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState, @Nullable PersistableBundle persistentState) {
        super.onCreate(savedInstanceState, persistentState);
        GiphyCoreUI.INSTANCE.configure(this, "API_KEY", true);
    }
}
```

**Comment by amiga** [comment]
wow thanks! thats awesome I didnt realise, im still new to Kotlin. Thank you.

**Comment by Crysis21** [comment]
you're welcome. closing this.
