### ISSUE TITLE
GifSelectionListener is not set properly after process death occurs

### ISSUE THREAD

**Issue by Zhuinden** [Giphy/giphy-android-sdk-ui-example#17]
In the following code:

https://github.com/Giphy/giphy-android-sdk-ui-example/blob/cebc9dd40cc7e45a5ba96b53b891de1dae9009a8/app/src/main/java/com/giphy/sdk/uidemo/DemoActivity.kt#L59

`dialog.gifSelectionListener = getGifSelectionListener()` is only executed only when the button is clicked.

However, the DialogFragment is recreated by the system after process death (refer to https://stackoverflow.com/questions/49046773/singleton-object-becomes-null-after-app-is-resumed/49107399#49107399), and the `gifSelectionListener` remains null. 

DialogFragments are meant to use the `setTargetFragment` API to allow callbacks to be made to the caller reliably even after process death.

----

Another option is to use the `tag` provided to `DialogFragment.show()` method to use `findFragmentByTag`, and set the `GifSelectionListener` in `onCreate` if the dialog exists. 

There is a good chance that the sample should represent that to avoid surprises.

**Comment by Crysis21** [comment]
Thanks for pointing this out. We will update the implementation

**Comment by Crysis21** [comment]
We added support for `setTargetFragment` API in release `1.2.2`
