### ISSUE TITLE
how to call  GiphyDialogFragment.newInstance().show(supportFragmentManager, "giphy_dialog")

### ISSUE THREAD

**Issue by amiga** [Giphy/giphy-android-sdk-ui-example#18]
how do I call this lien in java?

 GiphyDialogFragment.newInstance().show(supportFragmentManager, "giphy_dialog")

is newInstance() ? you really hsould supply examples in both java and kotlin, almoist no one knows kotlin yet

**Comment by amiga** [comment]
if i call using this i get a kotlin null pointer

GiphyDialogFragment frag = new GiphyDialogFragment();
                frag.show(HomeVideoFragment.supportFrag, "giphy_dialog");

**Comment by lulumahot** [comment]
Use it like this:
```
GPHSettings gphSettings = new GPHSettings();
GiphyDialogFragment gdl = GiphyDialogFragment.Companion.newInstance(gphSettings);
gdl.show();
```

**Comment by bogdantmm92** [comment]
@amiga please check @lulumahot example here. Unfortunately we don't currently have a timeline for adding Java documentation. 
Let us know if you managed to fix the issue, or if you need any other help.
Thanks!
