### ISSUE TITLE
giphy dialogFragment detached

### ISSUE THREAD

**Issue by dynamicBai** [Giphy/giphy-android-sdk-ui-example#19]
when call  GifsRecyclerview.configure,it will use fragment as ViewModelProvider lifecycle scope.
in some case,the fragment may be dettached,which cause exception.
And how can i aviod it, just check dialogFragment is attach before call show?
can this check logic handled by sdk?

**Comment by dynamicBai** [comment]
sdk version:v1.1.2

**Comment by bogdantmm92** [comment]
Hey @dynamicBai, thanks for your interest! We'll take a look and get back to you.

**Comment by Crysis21** [comment]
hey @dynamicBai we removed lifecycle from our latest SDK. please update to version 1.2.0 and let us know if you still have issues.

**Comment by dynamicBai** [comment]
> hey @dynamicBai we removed lifecycle from our latest SDK. please update to version 1.2.0 and let us know if you still have issues.

thanks,i will update sdk soon,and watch the crash from fabric.
