### ISSUE TITLE
Use SDK from Xamarin?

### ISSUE THREAD

**Issue by sam-piper** [Giphy/giphy-android-sdk-ui-example#20]
Hi, we'd like to apply for a production key for a chat app we're developing, we're investigating generating a verification code but our application is based on Xamarin Forms so we can't use your SDKs for iOS or Android directly at the moment as they are native-only.

Do you know of any way we could use for accessing your SDKs from Xamarin? Ideally a wrapper that allows the SDKs to be called from Xamarin using C# / Mono?

Thanks!

**Comment by Crysis21** [comment]
Hey sam-piper, could you provide more info about the wrapper for Xamarin?

**Comment by Crysis21** [comment]
Closing for now. Unless there is an easy way for us to provide Xamarin support, we will not engage in development for a hybrid solution at this moment.
