### ISSUE TITLE
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.giphy.sdk:ui:1.2.0. 

### ISSUE THREAD

**Issue by Nishit79** [Giphy/giphy-android-sdk-ui-example#21]
I cant able to resolve it (androidx articraft)
Android Studio - 3.3.5
Project - classpath 'com.android.tools.build:gradle:3.5.3'
Module Lib - implementation "com.giphy.sdk:ui:1.2.0"
Gradle Distribution Url - distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

**Comment by LaySoe** [comment]
Dear, service 
Thankfully

**Comment by Crysis21** [comment]
the latest version of the sdk is `com.giphy.sdk:ui:1.1.2`. You put the wrong version in your gradle file.
