### ISSUE TITLE
lightweight GiphyDialogFragment or .... pass GiphyDialogFragment a search string

### ISSUE THREAD

**Issue by martypants760** [Giphy/giphy-android-sdk-ui-example#22]
'm working on an app in which I'd like to show Gif content. I have obtained a test key and have successfully retrieved data from the search endPoint.
I am utilizing Speech to text as the search string.
My issues is how to display the data returned by the API on and Android phone. Attempting to use a gif url does not work well with Android ImageView or VideoViews (mp4). I was hoping the Giphy SDK would help, but that's got it's own search, which would confuse users as I want speech input. Is there a way to give GiphyDialogFragment the search string before it is created? Or maybe a smaller, subset UI to display a single media element?

**Comment by Crysis21** [comment]
Hey @martypants760 

we designed the UI SDK to offer View components for loading GIFs and rendering them. Once you receive a GIF, you have the `GPHMediaView` that you can use to render a GIF. You have all the info in the ReadMe file.

It seems that you are accessing the underlying implementation of the UI-SDK. We are deprecating those components and will no longer be available, so I'd suggest to use the Views and not the API directly.

**Comment by Crysis21** [comment]
please update to latest version 1.2.0 or newer
