### ISSUE TITLE
Giphy DialogFragment does not work with proguard / r8 enabled

### ISSUE THREAD

**Issue by Vitor238** [Giphy/giphy-android-sdk-ui-example#23]
When opening DialogFragment Gif with proguard / r8 enabled, the following message appears: "OH NO! SOMETHING WENT WRONG". What should I configure to work normally?

**Comment by Crysis21** [comment]
Hey @Vitor238 ,

We will have an update in the following days which fixes the proguard configuration.

Regards,
Cristian

**Comment by Crysis21** [comment]
should be fixed in 1.2.0
