### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by dynamicBai** [Giphy/giphy-android-sdk-ui-example#25]
version: android  v1.2.0
Exception:
com.giphy.sdk.ui.pagination.c cannot be cast to com.giphy.sdk.core.models.Media 

the stack is:
com.giphy.sdk.ui.views.GiphyDialogFragment.onGifPressed (GiphyDialogFragment.java:29)
com.giphy.sdk.ui.views.GiphyDialogFragment.access$onGifPressed (GiphyDialogFragment.java)
com.giphy.sdk.ui.views.GiphyDialogFragment$setupGifsRecycler$3.invoke (GiphyDialogFragment.java:9)
com.giphy.sdk.ui.views.GiphyDialogFragment$setupGifsRecycler$3.invoke (GiphyDialogFragment.java:8)
com.giphy.sdk.ui.universallist.c$f.onLongClick (c.java:25)

**Comment by Crysis21** [comment]
Hey @dynamicBai thanks for pointing this out. Looking into this issue.

**Comment by Crysis21** [comment]
@dynamicBai  I checked the issue and it happens when clicking/long-clicking on non-gif items, like the loading card / no-content card or the retry one. Can you confirm this? Fix will be available soon in 1.2.1

**Comment by dynamicBai** [comment]
Yes,Do what you say, this crash will appear

**Comment by Crysis21** [comment]
version `1.2.2` released
