### ISSUE TITLE
iphy/giphy-ios-sdk-ui-example] Binary XML file line #33: Binary XML file line #33: Error inflating class com.giphy.sdk.ui.views.GPHMediaView

### ISSUE THREAD

**Issue by iehsan77** [Giphy/giphy-android-sdk-ui-example#31]
i got this when i am trying to view animated gif in a

<com.giphy.sdk.ui.views.GifView
    android:layout_width=""
    android:layout_height=""

Process: com.example.smeschat, PID: 30706
    android.view.InflateException: Binary XML file line #54: Binary XML file line #54: Error inflating class com.giphy.sdk.ui.views.GifView
    Caused by: android.view.InflateException: Binary XML file line #54: Error inflating class com.giphy.sdk.ui.views.GifView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)

**Comment by Crysis21** [comment]
You are not importing the SDK correctly. What version are you using?

**Comment by iehsan77** [comment]
i am using   implementation "com.giphy.sdk:ui:1.2.5"

**Comment by Crysis21** [comment]
Please use `GPHMediaView` object, not `GifView`. That one is an internal object and not exposed. Where did you take the reference for it? It's not in the docs.

**Comment by ankitgrin** [comment]
I use GPHMediaView but i get Error inflating class com.giphy.sdk.ui.views.GPHMediaView
how can i solve it

**Comment by matteinn** [comment]
Make sure to init the SDK before @iehsan77 
`Giphy.configure(context, apiKey)`

**Comment by oussemaAr** [comment]
put the `Giphy.configure(this, YOUR_ANDROID_SDK_KEY)Giphy.configure(this, YOUR_ANDROID_SDK_KEY)` before inflating the layout inside the fragment

**Comment by annaharri89** [comment]
I am getting this same crash, but I'm already putting the configure call before I inflate the layout using com.giphy.sdk.ui.views.GPHMediaView

**Comment by yash292005** [comment]
hii i'm getting error "android.view.InflateException: Binary XML file line #13: Error inflating class com.giphy.sdk.ui.views.GiphyGridView"
and also i'm using a fragment pls help

**Comment by ALexanderLonsky** [comment]
@yash292005 we have the example app, it has `GridViewDemoActivity` and `DemoActivity` samples. Does it work for you?

Also, please refer [this](https://github.com/Giphy/giphy-android-sdk/blob/v2.0.6/Docs.md#basic-setup) documentation.

**Comment by yash292005** [comment]
Hii ALexander your idea worked just fine. but i'm having another issue
regarding the giphy, the url "http://giphy.bintray.com/giphy-sdk" is
showing  error 403 forbidden and due to this m can't compile my app do you
have any suggestion
? on how to fix it please suggest. thanks for reading

**Comment by ALexanderLonsky** [comment]
@yash292005 we have migrated from JCenter to MavenCentral:
https://search.maven.org/artifact/com.giphy.sdk/ui/2.1.0/aar

**Comment by yash292005** [comment]
Thanks, I will check it out.

**Comment by yash292005** [comment]
hii for some reason this is still not working this is my build.gradle(project level):
buildscript {
    ext.kotlin_version = "1.3.72"
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.1.3"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "http://giphy.bintray.com/giphy-sdk"
        }

    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

and i've implemented this line: 
implementation 'com.giphy.sdk:ui:2.1.0'
in my app level dependency
can you suggest what should i do thanks for your reading and your previous response.

**Comment by ALexanderLonsky** [comment]
@yash292005 please keep JCenter for now, you should remove this:
```
maven {
url "http://giphy.bintray.com/giphy-sdk"
}
```
and keep` JCenter + MavenCentral ` as here:
https://github.com/Giphy/giphy-android-sdk/blob/main/build.gradle.kts

Unfortunately, Blurkit and the latest Fresco version are not on Maven yet and it's required to keep JCenter for now

**Comment by yash292005** [comment]
hii i just wanted to know that can we share the gifs and other item the sdk has to offer over whatsapp or other social media using intent's start activity function?? ( IN THE GRID VIEW)

**Comment by ALexanderLonsky** [comment]
hey @yash292005, please, start a new topic for a new issue in the future. 
Giphy GridView does not provide a `Share` feature. 
But you can use the SDK to retrieve the `GPHMedia` that can be shared using [the Android Sharesheet](https://developer.android.com/training/sharing/send#send-binary-content)
