### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lcom/giphy/sdk/ui/r;

### ISSUE THREAD

**Issue by MobilefactoryAT** [Giphy/giphy-android-sdk-ui-example#32]
Details:
implementation 'com.giphy.sdk:ui:1.2.6'
Pixel 3a API 29 Emulator

Code:
```
 Giphy.configure(
                    context,
                    Settings.giphy_api(),
                    verificationMode = false
                )
```

Stack:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/giphy/sdk/ui/r;
        at com.giphy.sdk.ui.d.<init>(Unknown Source:30)
        at com.giphy.sdk.ui.c.<init>(Unknown Source:17)
        at com.giphy.sdk.ui.a.a(Unknown Source:45)
        at com.giphy.sdk.ui.l.a(Unknown Source:98)
        at com.giphy.sdk.ui.Giphy.configure(Unknown Source:81)
```

**Comment by Crysis21** [comment]
It seems there is an obfuscation problem, but it doesn't seem to be from the SDK. If you look at the starting point of the stack trace
```kotlin
        at com.giphy.sdk.ui.Giphy.configure(Unknown Source:81)
```
You will see it doesn't find a class that is passed as an argument. Baes on your code, I suspect there is a problem with  `Settings.giphy_api(),` object. Does this happen on release builds I suppose?

**Comment by MobilefactoryAT** [comment]
I just compiled again with implementation 'com.giphy.sdk:ui:1.2.5' and it worked.
No product is still in development there are no release builds.

**Comment by MobilefactoryAT** [comment]
hmm okey. I invalidated all cashes in Android studio now it works also with 1.2.6.
Seems that it was an issue from the compiler... sorry
