### ISSUE TITLE
No Class Def Exception

### ISSUE THREAD

**Issue by PiotrPrus** [Giphy/giphy-android-sdk-ui-example#34]
I got this error:
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/giphy/sdk/ui/r
that is pointing to my `Giphy.configure(this, BuildConfig.GIPHY_SDK_KEY)`. 
I believe the library is conflicting in some way with my other dependencies. When I made a clean new project with just basic dependencies, giphy SDK works as intended. In my big project with a lot of dependencies, it works only after cleaning `/build`, invalidate the cache and fresh install on the device.

**Comment by Crysis21** [comment]
I think there is a problem with they way you import dependencies. Can you print the dependencies list from gradle and see if Giphy UI SDK is in your dependency tree?

**Comment by PiotrPrus** [comment]
Hi @Crysis21, I have checked that. Giphy is there. I also tried downgrading the Giphy SDK and version 1.2.0 apparently works fine with my project.

**Comment by Crysis21** [comment]
Hi @PiotrPrus we discovered an issue with the SDK. We were repackaging the classes using `repackageclasses` in proguard. This led to all kind of issues to be seen in logs as part of our SDK, when in fact they were generated by other libraries. Releasing a fix today.

**Comment by Crysis21** [comment]
Please update to version 1.2.7

**Comment by PiotrPrus** [comment]
It is working. Thanks
