### ISSUE TITLE
The `gphCellPadding` in GiphyGridView is not working as intended

### ISSUE THREAD

**Issue by PiotrPrus** [Giphy/giphy-android-sdk-ui-example#36]
According to docs, the gphCellPadding can be used in XML as follows:
app:gphCellPadding="12dp". Unfortunately, setting value with `dp` is not possible. I got the error: "Cannot resolve symbol". As I looked through the class, the variable is set to an integer, so I am setting it as `12`.
This is not working either. The padding is still zero. I have checked the sample app and the `cellPadding` is not working for span = 1. When I set the span to 2, it is working fine. 
Is there any solution for that?

**Comment by Crysis21** [comment]
I've updated the padding to respect the DP size, otherwise it works as it should. Please update to `1.2.7`
