### ISSUE TITLE
Giphy Proguard Issue

### ISSUE THREAD

**Issue by Kranthi94** [Giphy/giphy-android-sdk-ui-example#37]
Hi,

We are using a latest version of GIPHY and alongside we are using socket client (https://github.com/socketio/socket.io-client-java) in our android app. When the network is fluctuating and the socket looses connection in socket connections callback information we are getting strange giphy sdk paths such as "com.giphy.sdk.ui.aq1: websocket error". What might be the issue here.?

Issue is not there until 1.2.0 version of GIPHY Android SDK.

Thanks in Advance.

**Comment by Crysis21** [comment]
hello, the issue is generated by a repackageclasses param we used in proguard. We've been notified by other developers as well. Today we will release a new update to fix this. Issues are not from giphy SDK, but all internal packages get repacked under ours. Sorry for the issues

**Comment by Crysis21** [comment]
Please update to version 1.2.7
