### ISSUE TITLE
SDK Demo not Available in Java

### ISSUE THREAD

**Issue by jbb-kryo** [Giphy/giphy-android-sdk-ui-example#38]
I'm trying to implement GIPHY SDK into my android app however I'm finding that your demo is pure Kotlin, half your documentation is in Java and also feels incomplete in term of missing steps. Can anyone give me any help on this one?

**Comment by Crysis21** [comment]
Documentation is full kotlin, not combined:
https://github.com/Giphy/giphy-android-sdk-ui-example/blob/master/Docs.md

What steps do you believe are missing in the docs? The SDK has been developed in `kotlin` but it's fully interoperable with `Java`.

**Comment by gaurav-kumar92** [comment]
@jbb-kryo have you found any example in java? I too am looking for an example in java. @Crysis21 If possible, please upload a java example for android. Thanks!

**Comment by BoumBam** [comment]
@Crysis21 I am too looking for example in java.
How to use it in java ?

Thanks.
*

**Comment by ALexanderLonsky** [comment]
Anyone who is facing this issue please find further discussion here: #66
