### ISSUE TITLE
Verification mode does not print out a Verification ID

### ISSUE THREAD

**Issue by polson** [Giphy/giphy-android-sdk-ui-example#39]
I'm using the Verification Instructions from [https://developers.giphy.com/docs/sdk/](https://developers.giphy.com/) which state that I should do the following to verify Giphy Integration:

> The first step is to obtain your Verification ID. Note that this is not the same as your API key. To get your ID, add the verificationMode parameter to the configure function like so:

The following sample code is suggested:
```
GiphyCoreUI.configure(context = yourContext,
 apiKey = “your api key”, verificationMode = true)
```

The first issue is that `GiphyCoreUI` is not a class, so I am doing this instead with my actual api key:

```
Giphy.configure(activity, "[myapikey]", verificationMode = true)
```

This runs successfully but does not print out any kind of verification ID to logcat.  How do I get a verification ID?

Here is the logcat output I see when running this command:
```
D/SoLoader: init start
D/SoLoader: adding system library source: /vendor/lib
D/SoLoader: adding system library source: /system/lib
D/SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.berd.qscore-t-5FRvLxzpQffvSQ89qtbg==/lib/arm64 flags = 0]
D/SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.berd.qscore/lib-main flags = 1]
D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.berd.qscore-t-5FRvLxzpQffvSQ89qtbg==/lib/arm64 flags = 0]
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.berd.qscore/lib-main flags = 1]
I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.berd.qscore/lib-main
D/SoLoader: init finish: 4 SO sources prepared
D/SoLoader: init exiting
D/MOAT: b0           configure
D/MOAT: b0           loadLibrary
```

I am testing on:
Pixel 2
Android 10
Giphy SDK version 1.2.6

**Comment by Crysis21** [comment]
Hi @polson,

Thanks for pointing out the issues in developer portal, I've asked the web team to update the docs. Latest instructions regarding android integration can always be found here:
https://github.com/Giphy/giphy-android-sdk-ui-example/blob/master/Docs.md

Please make sure you have Logging enabled on the Verbose level. From what I see, you are in Debug and I think this is what is causing your issue. It should look like this:
<img width="1105" alt="Screenshot 2020-05-01 at 14 08 57" src="https://user-images.githubusercontent.com/777169/80801540-71095580-8bb5-11ea-916f-65664f71879d.png">

**Comment by polson** [comment]
Oh wow, what a dumb mistake.  Thanks for pointing out that it was being logged at VERBOSE.
