### ISSUE TITLE
Aspect ratio missing in Media class

### ISSUE THREAD

**Issue by PiotrPrus** [Giphy/giphy-android-sdk-ui-example#46]
According to iOS docs: https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md#gphmediaview, there is a variable in media GPHMedia class called aspectRatio. 
Is it possible to add this field also to Media class in android SDK?

**Comment by PiotrPrus** [comment]
I have prepared an extension for aspectRatio. Can someone verify if I use proper variables from `Media` class?

`val Media.aspectRatio: Float
    get() {
        val width = this.images.downsized?.width
        val height = this.images.downsized?.height
        if (width == null || height == null) return 1f
        return width.div(height).toFloat()
    }`

**Comment by mihirmodiofficial** [comment]
Thanks, Please let me know how to remove chess background from transparent gif in GPHMediaView

**Comment by PiotrPrus** [comment]
Hi, I am not a Giphy SDK developer. I am trying to use it, but it has so many differences from iOS :(

**Comment by ALexanderLonsky** [comment]
@mihirmodiofficial thank you for flagging this issue and I'm sorry for late response. I'll add aspectRatio property in the next SDK release.
P.S. In iOS version we use "original" instead of "downsized".

**Comment by ALexanderLonsky** [comment]
@mihirmodiofficial This solved with 1.3.1 - going to close but let me know if that does not work for you.

**Comment by cuiti** [comment]
Hi @ALexanderLonsky , sorry to bring back this issue but I cannot access `aspectRatio` in the `Media` object that I get in `GifSelectionListener.onGifSelected()`.
I tried initially with 2.0.1, and then downgraded to 1.3.1, but still nothing. 
Any ideas?
