### ISSUE TITLE
Missing onError function

### ISSUE THREAD

**Issue by PiotrPrus** [Giphy/giphy-android-sdk-ui-example#49]
In iOS docs there is a function that checks the response for giphy by its ID:https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md#media-ids . It would be nice to have similar think for Android. Currentyl I do not know how to validate GiphyID. Is there any way to check that in current version (1.2.8)

**Comment by PiotrPrus** [comment]
ok, I found a callback that probably is used for that: `GifView.GifCallback`, but IMHO is not working. It works for proper mediaId, but for wrong mediaID the onFailure is not called.
@Crysis21 could you check it and update docs?

**Comment by bilalsoomro** [comment]
Same issue here. This is what I tried and the onFailure() method doesn't trigger if the media id doesn't exist or has been deleted from Giphy.
```
gifView.gifCallback = object : GifView.GifCallback {
    override fun onFailure(throwable: Throwable?) {
        Log.d("GIF Error")
    }
    override fun onImageSet(
        imageInfo: ImageInfo?,
        anim: Animatable?,
        loopDuration: Long,
        loopCount: Int
    ) {
        Log.d("GIF works")
      }
}

gifView.setMediaWithId(id, RenditionType.original)
```

**Comment by ALexanderLonsky** [comment]
@PiotrPrus, @bilalsoomro ,
Please try a new version 1.3.1:

```kotlin
mediaView.setMediaWithId(media.id) { result, e ->                
    e?.let {
        //your code here
    }
}  
```

Also there are two new methods to fetch gifs by IDs:
```kotlin
GPHCore.gifById(id) { result, e ->
    gifView.setMedia(result?.data, RenditionType.original)
    e?.let {
        //your code here
    }
}

GPHCore.gifsByIds(listOf(...)) { ... }
```

Please let me know if that works for you.

**Comment by bilalsoomro** [comment]
@ALexanderLonsky It works for me now. Thanks!
