### ISSUE TITLE
memory can't be recycled.

### ISSUE THREAD

**Issue by moo611** [Giphy/giphy-android-sdk-ui-example#51]
after dismissing the dialogfragment, the memory was increased by 40-50MB and can't be recycled

**Comment by ALexanderLonsky** [comment]
@moo611 thank you for flagging this.
We've removed leaks in version 1.3.1.

But those 40-50MB should be cache. When you close/open the `dialogfragment` many times, memory is not increasing constantly, it has upper threshold.

Under the hood the `GifView` uses `SimpleDraweeView` from `Fresco`
You can try to clear `Fresco` cache:
```
val pipeLine = Fresco.getImagePipeline()
pipeLine.clearMemoryCaches()
```

Please let me know if that works for you.

**Comment by moo611** [comment]
thanks
