### ISSUE TITLE
contentDidUpdate return zero

### ISSUE THREAD

**Issue by PiotrPrus** [Giphy/giphy-android-sdk-ui-example#54]
Here is the code snippet of my giphyGrid with callback:

`        binding.chatGiphyGrid.callback = object : GPHGridCallback {
            override fun contentDidUpdate(resultCount: Int) {
                Timber.i("Giphy carousel has been updated with quantity: $resultCount")
            }

            override fun didSelectMedia(media: Media) {
                viewModel.addGiphyToChat(media)
            }
        }`
The contentDidUpdate function is called twice for every invoke of `binding.chatGiphyGrid.content = GPHContent.searchQuery(query, MediaType.gif)`

The first value is always 0. I understand that giphyView is cleared every time a new query is made, but it would be nice to have additional info like LoadingStatus to know which zeros are the cleared state and which is actual final result of the query.

**Comment by ALexanderLonsky** [comment]
@PiotrPrus please try a new version 1.3.1, it's fixed there.
thank you!
