### ISSUE TITLE
No Matrix scaling support please add it

### ISSUE THREAD

**Issue by mihirmodiofficial** [Giphy/giphy-android-sdk-ui-example#57]
mGphMediaView..scaleType = ScalingUtils.ScaleType.Matrix 

 Please add support for matrix scaling

if your are providing below imageMatrix then why not scaling please add support for it

 (view as GPHMediaView).imageMatrix = matrix

**Comment by bogdantmm92** [comment]
Hey @mihirmodiofficial, under the hood the GifView uses SimpleDraweeView from fresco. [Here](https://frescolib.org/docs/scaletypes.html) you can find more details on how to apply custom scaling.

**Comment by mihirmodiofficial** [comment]
the problem is GPHMediaView is Final class so i cannot inherit to make a custom view to perform Drag Drop Rotate and Scaling.

**Comment by sportyjay92** [comment]
@mihirmodiofficial do you know any way I can drag and resize gif from Giphy ?

**Comment by mihirmodiofficial** [comment]
https://github.com/DroidNinja/Whatsapp-Like-PhotoEditor @sportyjay92  check out here i have implemented this

**Comment by ALexanderLonsky** [comment]
@mihirmodiofficial thank you fo flagging the issue, we'll make GPHMediaView inheritable in the next release.

**Comment by ALexanderLonsky** [comment]
@mihirmodiofficial please try a new version 1.3.1, `GPHMediaView` is open to subclassing now.
