### ISSUE TITLE
Limit results count

### ISSUE THREAD

**Issue by perracolabs** [Giphy/giphy-android-sdk-ui-example#60]
Is there any possible way to limit how many results are displayed/returned by GiphyDialogFragment?
I've checked in GPHSettings and couldn't find any property.
I saw that in the Web SDK there is a "limit" property.

**Comment by bogdantmm92** [comment]
Currently the sdk is built to display a paginated list of all gifs for a given query. Could you briefly explain why this functionality is important to you? Thanks

**Comment by perracolabs** [comment]
We have an app with our own built-in paid premium resources.
We are integrating Giphy to offer a large selection of free GIFs. 
The issue is that in order to not loose the value of our premium resources, and for users to still have a reason to purchase our app, we would need to limit the amount of Giphy's results.
Otherwise, if we give an unlimited result list from Giphy, then our product premium resources would become obsolete and loose its selling point.
By limiting Giphy's results it would be a balance between our premium resources and the Giphy's free gifs.

**Comment by cgmaier** [comment]
hey @perracolabs - thanks for opening this issue! unfortunately we can't support this use case in the SDK 

however, you can use the GIPHY API to achieve this experience 

good luck !
