### ISSUE TITLE
Remove network_security_config.xml

### ISSUE THREAD

**Issue by gildor** [Giphy/giphy-android-sdk-ui-example#61]
com.giphy.sdk:ui:1.2.8 (and earlier versions) includes network_security_config.xml which allows user-defined certificates for debug, and even worse allows cleartextTrafficPermitted.
This config applied to all apps which use the SDK, such behavior shouldn't be applied implicitly because decrease security level, it's true as for this sample, same as for SDK

**Comment by ALexanderLonsky** [comment]
@gildor thank you for flagging this. It's removed in [v1.3.2](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/v1.3.2)
