### ISSUE TITLE
Vertical Scrolling not happening in Giphy  android bottomsheet 

### ISSUE THREAD

**Issue by gouthamsivakumar1** [Giphy/giphy-android-sdk-ui-example#62]
<androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="fill_parent"
            android:background="@android:color/transparent">

            <FrameLayout
                android:id="@+id/frameTopLine"
                android:layout_width="@dimen/dimens48"
                android:layout_height="@dimen/dimens4"
                android:background="@drawable/bottomsheet_top_indicator"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <androidx.constraintlayout.widget.ConstraintLayout
                android:id="@+id/backGroundColor"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="@dimen/dimens8"
                android:background="@drawable/top_round_rectangle"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/frameTopLine">

                <include
                    android:id="@+id/searchViewAddress"
                    layout="@layout/search_bar_commonlayout"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/_56"
                    android:layout_marginTop="@dimen/_20"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />
              

                <androidx.recyclerview.widget.RecyclerView
                    android:id="@+id/recyclerViewCategory"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:clipToPadding="false"
                    android:orientation="horizontal"
                    android:paddingStart="@dimen/dimens24"
                    android:paddingEnd="@dimen/dimens24"
                    app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toBottomOf="@+id/searchViewAddress"
                    tools:listitem="@layout/upload_video_list_catgory_item" />

                

                <com.giphy.sdk.ui.views.GiphyGridView
                    android:id="@+id/giphyGridView"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="@dimen/dimens16"
                    android:minHeight="@dimen/_100"
                    app:gphCellPadding="@dimen/_12"
                    app:gphDirection="vertical"
                    app:gphShowCheckeredBackground="false"
                    app:gphSpanCount="2"
                    app:gphUseInExtensions="false"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintHorizontal_bias="0.0"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toBottomOf="@+id/recyclerViewCategory"
                    app:layout_constraintVertical_bias="1.0" />
                

            </androidx.constraintlayout.widget.ConstraintLayout>

        </androidx.constraintlayout.widget.ConstraintLayout>
</layout>

**Comment by bogdantmm92** [comment]
hey @gouthamsivakumar1, could you please share an image of what you're trying to accomplish with the UI SDK?

**Comment by gouthamsivakumar1** [comment]
[
![Screenshot from 2020-07-07 18-33-23](https://user-images.githubusercontent.com/22275806/86785577-78028780-c080-11ea-9356-b3df7cda717b.png)
](url)

**Comment by bogdantmm92** [comment]
Some other view in your layout might intercept touch views. Any reason you're not using GiphyDialogFragment directly as in the example?

**Comment by gouthamsivakumar1** [comment]
hi , for some UI customization i needed to change it to BottomSheetDialogFragment .but when i used  gridview direction in  horizontal it is working fine .

**Comment by bogdantmm92** [comment]
Yes, I would make sure you don't have other vertical scroll elements except the giphy grid.

**Comment by gouthamsivakumar1** [comment]
![Screenshot_20200720-164513](https://user-images.githubusercontent.com/22275806/87932173-b3517d00-caa8-11ea-9bd1-50b8a4f5b145.jpg) . i can't do the vertical scroll in it
