### ISSUE TITLE
How to set the default active GPHContentType?

### ISSUE THREAD

**Issue by perracolabs** [Giphy/giphy-android-sdk-ui-example#63]
When configuring **GiphyDialogFragment** with a list of **GPHContentType**(s), how to define which is the default active one?

The ideal would be to be able to restore the most recently used content type the next time **GiphyDialogFragment** gets opened again, as the user may have predilection for such specific content type.

Maybe a solution would be to add a new extra parameter in **GPHSettings.setMediaTypeConfig()**, defining the default active index from the passed **GPHContentType** array?

By the way, not sure if this is a bug, but in the callback **onGifSelected** the **Media parameter** always returns a **MediaType** set to **GIF**, never to emoji, text, etc., which would help to know what the user selected.

**Comment by ALexanderLonsky** [comment]
@perracolabs, thanks for flagging this, we'll look into it and get back to you.

**Comment by ALexanderLonsky** [comment]
@perracolabs please try a new version #1.3.1:
[settings](https://github.com/Giphy/giphy-android-sdk-ui-example/blob/master/Docs.md#gphsettings-properties)
`settings.selectedContentType = GPHContentType.emoji`

**Comment by ALexanderLonsky** [comment]
This solved with 1.3.1 - going to close but let me know if you still have trouble : )
