### ISSUE TITLE
Tabs are overlapping when using long text localizations

### ISSUE THREAD

**Issue by perracolabs** [Giphy/giphy-android-sdk-ui-example#64]
As Giphy isn't localized besides english, we are making the translations ourselves by overriding the "gph_" related strings for all our supported languages.
We've found that the tabs will span over the others when the text is too long. See the next example with a Russian localization. The "results" string overlaps the "recents" string

Recents = Недавние
Results = результатов

![image](https://user-images.githubusercontent.com/7354233/86932661-f1aa7c00-c139-11ea-9501-35ea839fb50b.png)

**Comment by BoumBam** [comment]
I have same problem.
Did you find any solution ?

Thanks.

**Comment by perracolabs** [comment]
@BoumBam Ended up removing the "Results" string part and leaving only "%1$d", so instead it only appears the total number.

**Comment by ALexanderLonsky** [comment]
@perracolabs , @BoumBam thanks for raising this, we are on it and will get back to you soon.

**Comment by ALexanderLonsky** [comment]
@perracolabs , @BoumBam please try a new version: "com.giphy.sdk:ui:1.2.9". We've removed the "results" string.
