### ISSUE TITLE
Error trying to use it in java file

### ISSUE THREAD

**Issue by BoumBam** [Giphy/giphy-android-sdk-ui-example#66]
I want to use that Giphy in my 100% java  android project
When I use that code in kotlin file it works fine.
`   Giphy.configure(this, "key")
    GiphyDialogFragment.newInstance().show(supportFragmentManager, "giphy_dialog") `

But when I am in java file:
**configure** is red marked with message: non static'confirgure(android.content.@org.jetBrainsAnnotation. NonNull conntext ......)' cannot be refernced from a static context

**newInstance()** newInstance Cannot resolve method(newInstance)

**supportFragmentManager** cannot reslove symbole(supportFragmentManager)

How to use it in java ?
Thanks for your nice work.

**Comment by perracolabs** [comment]
@BoumBam Try the next snippet. Notice that for **Giphy.INSTANCE.configure**, you must set to **True** the third parameter only when you need to verify your developer's key. After they verify your key then set it always to **False**.

```
@NonNull 
public GiphyDialogFragment show(@NonNull final AppCompatActivity parent, final  boolean withDarkTheme,
		 @NonNull final String apiKey, @NonNull final  GiphyDialogFragment.GifSelectionListener listener)
{
	Giphy.INSTANCE.configure(parent, apiKey, false);
	
	final GPHTheme theme = (withDarkTheme)
			? GPHTheme.Dark
			: GPHTheme.Light;

	final GPHSettings settings = new GPHSettings();
	settings.setTheme(theme);
	settings.setRating(RatingType.pg13);
	settings.setRenditionType(RenditionType.fixedWidth);
	settings.setGridType(GridType.waterfall);
	settings.setShowCheckeredBackground(true);

	final GPHContentType[] contentTypes = new GPHContentType[5];
	contentTypes[0] = GPHContentType.sticker;
	contentTypes[1] = GPHContentType.gif;
	contentTypes[2] = GPHContentType.text;
	contentTypes[3] = GPHContentType.emoji;
	contentTypes[4] = GPHContentType.recents;
	settings.setMediaTypeConfig(contentTypes);

	final GiphyDialogFragment dialog = GiphyDialogFragment.Companion.newInstance(settings);
	dialog.setGifSelectionListener(listener);
	
	final FragmentManager fragmentManager = parent.getSupportFragmentManager();
	dialog.show(fragmentManager, "giphy");

	return dialog;
}
```

**Comment by BoumBam** [comment]
@perracolabs Thanks guy I would never be able to find solution for that if you did not help me.

I have another question if you have time:
How could I get the src file source name of the selected gif (something like: **https://media0.giphy.com/media/bbshzgyFQDqPHXBo4c/giphy.gif)** ?

I want to show the selected gif in an ImageView.

Thanks.

**Comment by perracolabs** [comment]
In the **null** parameter pass the **listener** that will receive the selection callback.
For example, in your Fragment, Activity or a dedicated class, implement the listener interface and pass the instance as the listener.

About getting the GIF into an **ImageView**, there are several ways, but the simplest is to use [Glide](https://github.com/bumptech/glide), or [Fresco](https://github.com/facebook/fresco).

Next an example with some explanation comments. Notice it implements the callback listener, so you would need to pass that class instance as the listener parameter to the show method.
Let me know if something isn't clear.

```
public class YourClassActivityOrFragment implements GiphyDialogFragment.GifSelectionListener
{

	@Override
	public void onGifSelected(@NotNull final Media media, @Nullable final String search)
	{
		// Here we choose the preferred GIF size to get according to the requirements.
		// In this example we choose getFixedWidth to limit the GIF into a 200px width boundary.
		// Using getOriginal will give the full sized GIF, but consider that it will be downloaded,
		// and a GIF file may have a few megabytes.
		// Check Gipy's documentation about the different redention sizes and best practices: 
		// https://developers.giphy.com/docs/optional-settings/#rendition-guide
		final Image image = media
				.getImages()
				.getFixedWidth();

		// Get the GIF's download url 
		final String url = image.getGifUrl();

		// A very simple and straight example with Glide downloading,
		// caching, and setting the GIF into an ImageView.
		Glide.with(context)
			.load(url)
			.into(YourImageView);
	}
}
```

**Comment by BoumBam** [comment]
Thanks a lot for your time. Work great. Be blessed.
