### ISSUE TITLE
How to customize the default dialog ?

### ISSUE THREAD

**Issue by BoumBam** [Giphy/giphy-android-sdk-ui-example#67]
Hello,
I have image below:

![109379939_2693162354286667_733316393486823672_o](https://user-images.githubusercontent.com/26336351/87607632-50996380-c6ed-11ea-9f2c-69f18ac392fc.jpg)

I want to customize the default dialog.

Using java:

My app will be translated in 5 languages,  How could I change the red marked texts ?
How coul I replace the red marked serch icon ?
How could I change the backgroundColor and the textColor of the button **Retry** ?

Thanks in advance for any help.

**Comment by perracolabs** [comment]
@BoumBam You need to override Giphy's strings in your **strings.xml** localization files. 
Copy paste the strings bellow to get you started.
In addition, if you press the Ctrl key + Click over one of these strings once are in your project **strings.xml** file, then Android Studio will give you the choice to navigate into the original Giphy's file. There you can select other values that you wish to override by placing them into your corresponding project files (so colors into colors.xml, strings into strings.xml, etc), so they take preference over the Giphy ones.

Next some strings, copy+paste them into your strings.xml:
```
    <string name="gph_attibution_back">Back</string>
    <string name="gph_choose_emoji">Select Emoji</string>
    <string name="gph_choose_gif">Select GIF</string>
    <string name="gph_choose_sticker">Select Sticker</string>
    <string name="gph_copy">Copy</string>
    <string name="gph_copy_link">Copy Link</string>
    <string name="gph_emoji">Emoji</string>
    <string name="gph_error_generic_list_loading">Oh NO! Something Went Wrong.</string>
    <string name="gph_error_no_gifs_found">No GIFs found</string>
    <string name="gph_gifs">GIFs</string>
    <string name="gph_more_by">More by @%1$s</string>
    <string name="gph_more_creator">See more by creator</string>
    <string name="gph_recents">Recents</string>
    <string name="gph_remove">Remove</string>
    <string name="gph_results_count">%1$d results</string>
    <string name="gph_retry">Retry</string>
    <string name="gph_search_giphy">Search GIPHY</string>
    <string name="gph_search_giphy_stickers">Search GIPHY Stickers</string>
    <string name="gph_search_giphy_text">Search GIPHY Text</string>
    <string name="gph_share">Share</string>
    <string name="gph_stickers">Stickers</string>
    <string name="gph_text">Text</string>
    <string name="gph_view_on_giphy">View on GIPHY</string>
```

**Comment by BoumBam** [comment]
Hello again,
I tried to get the imageView of the serch icon to cchange it with:
`LayoutInflater factory = getLayoutInflater();
         View new_post_background_image = factory.inflate(R.layout.gph_search_bar_full, null);
        ImageView imageView = new_post_background_image.findViewById(R.id.performSearchBtn);`

But I see error:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.e.emoji/com.e.emoji.MainActivity}: android.view.InflateException: Binary XML file line #2: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: android.view.InflateException: Binary XML file line #2: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
     Caused by: android.view.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
        at com.e.emoji.MainActivity.onCreate(MainActivity.java:89)`

It seems like that icon cannot be changed.

I also searched in `values` file you have talked me about, But I cannot see the part of the button retry to change it style.

With all these questions, You can understand I'm not an experienced programmer. In fact I'm working on my first app.

Big Thanks.

**Comment by perracolabs** [comment]
@BoumBam Instead of changing the ImageView icon by accessing the View, try instead to override the icon itself.
 
I am no sure it will work because it will depend in other facts such as if they perform some changes by code. But, the way to do it is to override the used resources  by creating the files in your project with the same names as the ones in Giphy, this way your files take priority.
Take into account that you must create all the necessary files for each required density folder, so if Giphy has an icon in hdpi, mdpi, xhdpi, etc, then you must also put your override file into all these folders within your project. 

For the search I looked the layout in Giphy and seems to be these:

 For the search gradient background seems to be only 1 xml file in the drawable folder
@drawable/gph_search_btn_bg

For the search icon itself seems to be png in several density folders, open the layout and press Ctrl+Click over the icon drawable to see them:
@drawable/gph_ic_search_white

**Comment by BoumBam** [comment]
I copied all the content of `res` folder and edited `gph_search_btn_bg.xml` by:

`<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:angle="45"
        android:endColor="#000000"
        android:startColor="#000000" />
</shape>`

But no change.
The search icon color has same color, it's not getting black color as i want.

Thanks.

**Comment by PasqualePuzio** [comment]
I would like to have more customization options too.

**Comment by ALexanderLonsky** [comment]
@BoumBam I am sorry for the late reply.

to customise the search bar colors:
```
<color name="gph_blurred_search_bar_background_light">#F1F1F1</color>
<color name="gph_search_bar_background_light">#ECECEC</color>
<color name="gph_search_bar_background_dark">#4E4E4E</color>
<color name="gph_blurred_search_bar_background_dark">#E1666666</color>
<color name="gph_search_query_light">#5C5C5C</color>
<color name="gph_search_query_dark">#ffffff</color>
```

The retry button uses 
`style="@style/Widget.AppCompat.Button.Colored"`

so to customise it:
```
<style name="Widget.AppCompat.Button.Colored">
        <item name="android:textColor">@color/colorPrimaryDark</item>
        <item name="android:textSize">16dp</item>
        <item name="android:background">@color/black</item>
    </style>
```
