### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0

### ISSUE THREAD

**Issue by wiggisser** [Giphy/giphy-android-sdk-ui-example#68]
In the docs, you state to add the giphy SDK as follows

    maven {
        url "http://giphy.bintray.com/giphy-sdk"
    }

When I do this, I get the following warning in the build:

> Using insecure protocols with repositories has been deprecated. This is scheduled to be removed in Gradle 7.0. Switch Maven repository 'maven2(http://giphy.bintray.com/giphy-sdk)' to a secure protocol (like HTTPS) or allow insecure protocols, see https://docs.gradle.org/6.1.1/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol.

It works if I use 

    maven {
        url "https://giphy.bintray.com/giphy-sdk"
    }

instead. Please adapt the docs accordingly ...

**Comment by ALexanderLonsky** [comment]
@wiggisser thanks for flagging this, we will update the documentation.

**Comment by ALexanderLonsky** [comment]
@wiggisser the documentation is updated, thanks!

**Comment by wiggisser** [comment]
https://developers.giphy.com/docs/sdk#android

is still pointing to `http://giphy.bintray.com/giphy-sdk`
