### ISSUE TITLE
Get frames of Media onGifSelected

### ISSUE THREAD

**Issue by WildSpirit007** [Giphy/giphy-android-sdk-ui-example#70]
I am working on Giphy on Android. It is working fine

I want to know if there is any way to extract the media frames (i.e as list of Bitmaps ) when a gif is selected.

Thank you

**Comment by ALexanderLonsky** [comment]
hey @WildSpirit007,

We don't provide this out-of-the-box.

You should handle GIF selection. For doing that you need to implement the GifSelectionListener interface. 
Please find more details [here](https://github.com/Giphy/giphy-android-sdk-ui-example/blob/master/Docs.md).
Then you can retrieve an url to a gif like
`media.images.fixedWidth.gifUrl`

And now you can achieve your goal using any solution like:

[ImageIO](https://stackoverflow.com/a/10627458/2851872)
[Fresco](https://github.com/facebook/fresco/issues/2229#issuecomment-434061873)
[android-gif-drawable](https://github.com/koral--/android-gif-drawable)
