### ISSUE TITLE
Can't search over emojis

### ISSUE THREAD

**Issue by amitkle** [Giphy/giphy-android-sdk-ui-example#71]
Hey,
I'm not sure if it is a bug, but I can't search over emojis. It is automatically search over gifs (I'm passing MediaType.emoji)
Showing the trending does work.

**Comment by cgmaier** [comment]
hey @amitkle - that's the correct behavior. the set of emojis aren't searchable at the moment

**Comment by amitkle** [comment]
Ok thanks :)
