### ISSUE TITLE
Checkered backgound...

### ISSUE THREAD

**Issue by barsbaatar2** [Giphy/giphy-android-sdk-ui-example#79]
I am using Giphy SDK in java. 
 **_The problem is my gif.s background is not transparent but checkered._**
![118099391_925334711277678_2018644654064040746_n](https://user-images.githubusercontent.com/59549374/90865903-b3a1a880-e3c5-11ea-9f6a-da2c9a8d4a6e.jpg)

In some reason such as passed by API, I am using mediaID of GIF to display. 
```
GPHCore.INSTANCE.gifById(mediaID, (mediaResponse, throwable) -> {
                giphy.setMedia(mediaResponse.getData(), RenditionType.fixedWidth,null);
                return null;
            });
```
and also used
`giphy.setMediaWithId(mediaID, null, null, null);`
It also displays checkered backgrounded GIFs.

### **The question is how to set transparent background?**

**Comment by barsbaatar2** [comment]
for emoji: QTxCEgcvorSGCSXxKE
for sticker: TKYOsg7Ebrp1Uycacd

**Comment by ALexanderLonsky** [comment]
@barsbaatar2 please try to set 
`giphy.isBackgroundVisible = false`

**Comment by barsbaatar2** [comment]
That worked... Thanks a lot for your support
