### ISSUE TITLE
GPHMediaView wrap_content is not effective outside RecyclerView

### ISSUE THREAD

**Issue by BattleShipPark** [Giphy/giphy-android-sdk-ui-example#9]
Hi, I am trying your example and it works well.
The example show images with GPHMediaView inside RecyclerView, but I don't need RecyclerView. I added GPHMediaView like this:

    <com.giphy.sdk.ui.views.GPHMediaView
            android:id="@+id/mediaView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_constraintBottom_toTopOf="@+id/composeContainer"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/toolbar2" />

    <android.support.v7.widget.RecyclerView
        android:id="@+id/messageFeed"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_marginBottom="8dp"
        app:layout_constraintBottom_toTopOf="@+id/composeContainer"
        app:layout_constraintTop_toBottomOf="@+id/toolbar2" />

and modifyed listener like this:

    private fun getGifSelectionListener() = object : GiphyDialogFragment.GifSelectionListener {
        override fun onDismissed() {
            Log.d(TAG, "onDismissed")
        }

        override fun onGifSelected(media: Media) {
            Log.d(TAG, "onGifSelected")
            mediaView.setMedia(media)
        }
    }

Then the image fills the screen like this:
![device-2019-09-11-145751](https://user-images.githubusercontent.com/10345980/64671825-97527780-d4a4-11e9-85e1-d13eea75bd6a.png)

What is the problem?

Thanks.

**Comment by Crysis21** [comment]
We wrote a new way of how we measure the `GifView` component. Soon it will be available in a new update.

**Comment by Crysis21** [comment]
version `1.2.2` released and fixes this issue.
