### ISSUE TITLE
Disable suggestions

### ISSUE THREAD

**Issue by jetsekoopmans** [Giphy/giphy-android-sdk-ui-example#91]
GIPHY SDK Version: 2.0.3

How do I disable the suggestions/trending keywords that appear below the search bar and above the GIF's?

**Comment by ALexanderLonsky** [comment]
@jetsekoopmans there is no option to do that now, but we'll provide it soon.

**Comment by jetsekoopmans** [comment]
Nice, thanks! Any ETA? :)

**Comment by ALexanderLonsky** [comment]
@jetsekoopmans I am sorry, I've missed your message :(
Please try this version: `com.giphy.sdk:ui:2.0.3-suggestions-on-off`

`GiphyDialogFragment.newInstance(settings.copy(showSuggestionsBar = false))`

**Comment by jetsekoopmans** [comment]
It works like a charm, thanks!!
