### ISSUE TITLE
onGifSelected in fragment does not work

### ISSUE THREAD

**Issue by BoumBam** [Giphy/giphy-android-sdk-ui-example#93]
When showing the GiphyDialogFragment in fragment, after clicking on a gif the `onGifSelected ` method is not called and I can't get the gif Url.
It works fine when I'm in an Activity.
Any solution ?

**Comment by ALexanderLonsky** [comment]
@BoumBam could you check please if [this](https://github.com/Giphy/giphy-android-sdk-ui-example/blob/master/Docs.md#gifselectionlistener-technical-note) helps?

**Comment by BoumBam** [comment]
@ALexanderLonsky Thanks, I already solved it.
