### ISSUE TITLE
Remove button not visible

### ISSUE THREAD

**Issue by sathishmscict** [Giphy/giphy-android-sdk-ui-example#96]
"Remove" button not visible for some of gif images from "Recent" tab. Please review below images for more information :

![image](https://user-images.githubusercontent.com/18158746/98257915-3dfdaf80-1fa6-11eb-8137-55ea32a83265.png)

![image](https://user-images.githubusercontent.com/18158746/98257942-48b84480-1fa6-11eb-9c9b-7898816600fe.png)

![image](https://user-images.githubusercontent.com/18158746/98257973-51a91600-1fa6-11eb-8219-30d799d06331.png)

Here ,
1. First image have only 2 options in context menu , so it could be easily clickable and remove option working fine.
2. Second image have 3 options , so difficult to click on "Remove"  option. But anyway it is clickable and remove option working fine.
3. Coming to third image "Remove" option not visible. So,  unable to perform "Remove" option in this case.

**Comment by ALexanderLonsky** [comment]
@sathishmscict thank you for flagging this, I'll take a look.

**Comment by ALexanderLonsky** [comment]
@sathishmscict please try [v2.0.5](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/v2.0.5).

**Comment by sathishmscict** [comment]
Thank you @ALexanderLonsky . Its working as expected.
![RemoveButton](https://user-images.githubusercontent.com/18158746/98890553-454f1c80-24c2-11eb-8a5d-48905254c985.JPG)

**Comment by sathishmscict** [comment]
Hi @ALexanderLonsky ,after removing the all gif images is showing "Retry" button on center of the screen.

![image](https://user-images.githubusercontent.com/18158746/99217843-07723100-27ff-11eb-8d4d-6bf61d223e86.png)

**Comment by ALexanderLonsky** [comment]
@sathishmscict hi, try please this version:
`com.giphy.sdk:ui:2.0.5-recents-fix`

**Comment by sathishmscict** [comment]
Hi @ALexanderLonsky  , now its working fine. We are closed this issue. Thank you for quick response, appreciated.
![image](https://user-images.githubusercontent.com/18158746/99346747-64332180-28bb-11eb-96d6-e778c2311700.png)
