### ISSUE TITLE
How to customize font and button background color in dialog

### ISSUE THREAD

**Issue by PasqualePuzio** [Giphy/giphy-android-sdk-ui-example#97]
Hi,

we would like to customize some details in the dialog such as the font of the dialog and the buttons background color.

Is there a recommended or even undocumented way to achieve this?

Thanks

![gif2](https://user-images.githubusercontent.com/7646303/98348905-9cb04100-2019-11eb-9702-c67accf72224.png)
![gif1](https://user-images.githubusercontent.com/7646303/98348919-a0dc5e80-2019-11eb-8357-f892b29e4321.png)

**Comment by ALexanderLonsky** [comment]
Hi @PasqualePuzio, I'll take a look and let you know.

**Comment by ALexanderLonsky** [comment]
@PasqualePuzio you can customise the button background color by overriding the following resources:
```
<color name="gph_purple_btn_selected">#36318f</color>
<color name="gph_purple_btn">#6157ff</color>
```
also you can customise the search bar colors:
<color name="gph_blurred_search_bar_background_light">#F1F1F1</color>
<color name="gph_search_bar_background_light">#ECECEC</color>
<color name="gph_search_bar_background_dark">#4E4E4E</color>
<color name="gph_blurred_search_bar_background_dark">#E1666666</color>
<color name="gph_search_query_light">#5C5C5C</color>
<color name="gph_search_query_dark">#ffffff</color>

Unfortunately, there is no possibility to customise fonts at this time.
