### ISSUE TITLE
Panning GPHMediaView

### ISSUE THREAD

**Issue by VittoriDavide** [Giphy/giphy-android-sdk-ui-example#99]
Hello, 

I have been using the library to implement an Activity where I can add gifs and drag them all over the screen. 

The problem is that the GPHMediaView is not letting pass the touch event to the upper view making it impossible to handle the touch event with this component. Do you think there is any way to handle this error?

**Comment by ALexanderLonsky** [comment]
@VittoriDavide it would be great to share your example.
I've just tried to drag `GPHMediaView` using:
```
val listener = View.OnTouchListener(function = { view, motionEvent -> 
...
})
mediaView.setOnTouchListener(listener)
```
and it works for me.

**Comment by VittoriDavide** [comment]
Yes, is true.
 Adding the OnTouchListener to `GPHMediaView` , instead I was adding it to a `LinearLayout` that contained the `GPHMediaView`, but the touch event were blocked. 

Thanks for your feedback
